// Syncs the static site into the WordPress theme + companion plugin.
//   npm run build:wp
//
// - copies CSS / JS / images / media into the theme (pixel parity by construction)
// - generates PHP fragments for the decorative animated scenes, icon set and map
// - exports all catalogue data (plans, locations, reviews, FAQs, menus…) as JSON,
//   used by the theme as fallback content and by the plugin's demo importer.

import { cpSync, mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICONS } from '../src/lib/icons.mjs';
import { scenes, techVisual } from '../src/lib/components.mjs';
import { MAP, EUROPE, WORLD_PATH, EUROPE_PATH } from '../src/data/world-dots.mjs';
import { MEDIA } from '../src/data/media.mjs';
import { site, nav, footer } from '../src/data/site.mjs';
import { products } from '../src/data/products.mjs';
import { homeFaqs, reviews, locations, posts, kb, tutorials, statusServices, references } from '../src/data/content.mjs';
import { readFileSync } from 'node:fs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const theme = join(root, 'wordpress/themes/rmdhost');
const plugin = join(root, 'wordpress/plugins/rmdhost-core');
const php = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const HEAD = '<?php\n/**\n * GENERATED by scripts/build-wp.mjs – do not edit by hand.\n *\n * @package RMDHost\n */\n\ndefined( \'ABSPATH\' ) || exit;\n';

const write = (file, content) => { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, content); };

// 1. Assets ------------------------------------------------------------------
const assets = join(root, 'src/static/assets');
for (const d of ['css', 'js', 'img', 'media']) {
  const target = join(theme, 'assets', d === 'css' ? 'css' : d, d === 'css' ? '' : '');
  if (d === 'css') write(join(theme, 'assets/css/main.css'), readFileSync(join(assets, 'css/main.css'), 'utf8'));
  else if (d === 'js') write(join(theme, 'assets/js/main.js'), readFileSync(join(assets, 'js/main.js'), 'utf8'));
  else {
    if (existsSync(target)) rmSync(target, { recursive: true });
    cpSync(join(assets, d), target, { recursive: true });
  }
}

// 2. Icons -------------------------------------------------------------------
write(join(theme, 'inc/generated/icons.php'),
  `${HEAD}\nreturn array(\n${Object.entries(ICONS).map(([k, v]) => `\t${php(k)} => ${php(v)},`).join('\n')}\n);\n`);

// 3. Decorative scenes (aria-hidden mock UIs) ------------------------------------
for (const [name, fn] of Object.entries(scenes)) {
  write(join(theme, `template-parts/scenes/${name}.php`), `${HEAD}?>\n${fn().trim()}\n`);
}
for (const kind of ['linux', 'windows', 'rack', 'storage']) {
  write(join(theme, `template-parts/scenes/tech-${kind}.php`), `${HEAD}?>\n${techVisual(kind).trim()}\n`);
}

// 4. Map + media manifest ---------------------------------------------------------
write(join(theme, 'inc/generated/map.php'),
  `${HEAD}\nreturn array(\n\t'map'    => array( 'w' => ${MAP.w}, 'h' => ${MAP.h}, 'lat_top' => ${MAP.latTop}, 'lat_bottom' => ${MAP.latBottom} ),\n\t'europe' => array( 'lon_min' => ${EUROPE.lonMin}, 'lon_max' => ${EUROPE.lonMax}, 'lat_min' => ${EUROPE.latMin}, 'lat_max' => ${EUROPE.latMax} ),\n\t'world'  => ${php(WORLD_PATH)},\n\t'eu'     => ${php(EUROPE_PATH)},\n);\n`);
write(join(theme, 'inc/generated/media.php'),
  `${HEAD}\nreturn array(\n${Object.entries(MEDIA).map(([k, v]) => `\t${php(k)} => array( 'w' => ${v.w}, 'h' => ${v.h}, 'small' => ${v.small || 0} ),`).join('\n')}\n);\n`);

// 5. Catalogue (fallback content + demo data) -----------------------------------------
const homepage = JSON.parse(readFileSync(join(root, 'src/data/homepage.json'), 'utf8'));
delete homepage._help;
const catalog = {
  version: 1,
  site: {
    name: site.name, email: site.email, salesEmail: site.salesEmail, clientArea: site.clientArea,
    loginUrl: site.loginUrl, orderFallback: site.orderFallback, domainSearchUrl: site.domainSearchUrl,
    ticketUrl: site.ticketUrl, currency: site.currency, social: site.social, stats: site.stats,
  },
  homepage,
  nav,
  footer: footer.map((c) => ({ title: c.title, links: c.links.map(([label, href]) => ({ label, href: href === 'CLIENT_AREA' ? site.loginUrl : href })) })),
  products: products.map((p) => ({ ...p, plans: p.plans.map((pl) => ({ ...pl })) })),
  faqs: homeFaqs.map(([q, a]) => ({ q, a })),
  reviews, locations, posts, kb, tutorials, statusServices, references,
};
const json = JSON.stringify(catalog, null, 1);
write(join(theme, 'inc/data/catalog.json'), json);
write(join(plugin, 'demo/catalog.json'), json);

// Legal page bodies for the demo importer (prose only, no hero).
const { default: pages } = await import('../src/pages/pages.mjs');
const legal = {};
for (const pg of pages.filter((x) => ['/privacy-policy/', '/terms-of-service/', '/cookie-policy/'].includes(x.path))) {
  const m = pg.body().match(/<div class="container narrow prose">([\s\S]*?)<\/div><\/section>/);
  legal[pg.path.replace(/\//g, '')] = { title: ((t) => t.charAt(0) + t.slice(1).toLowerCase())(pg.title.split(' | ')[0]), excerpt: pg.description, html: m ? m[1].trim() : '' };
}
write(join(plugin, 'demo/legal.json'), JSON.stringify(legal, null, 1));

console.log(`WordPress theme synced: ${Object.keys(scenes).length + 4} scenes, ${Object.keys(ICONS).length} icons, ${products.length} products.`);
