// Generates src/data/world-dots.mjs – a dotted world map used by the
// data-centre sections. Only needs to run again if you change the grid.
//
//   curl -sSLo land.json https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/land-110m.json
//   node scripts/make-map.mjs land.json

import { readFileSync, writeFileSync } from 'node:fs';

const [, , file] = process.argv;
if (!file) throw new Error('usage: node scripts/make-map.mjs land-110m.json');
const topo = JSON.parse(readFileSync(file, 'utf8'));
const { scale, translate } = topo.transform;

// Decode delta-encoded arcs into lon/lat points.
const arcs = topo.arcs.map((arc) => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => {
    x += dx; y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});
const ring = (ids) => ids.flatMap((i) => (i < 0 ? arcs[~i].slice().reverse() : arcs[i]));

const polygons = [];
for (const g of topo.objects.land.geometries) {
  const polys = g.type === 'Polygon' ? [g.arcs] : g.arcs;
  for (const p of polys) polygons.push(p.map(ring));
}

function inRing(pt, r) {
  let inside = false;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
    const [xi, yi] = r[i], [xj, yj] = r[j];
    if ((yi > pt[1]) !== (yj > pt[1]) && pt[0] < ((xj - xi) * (pt[1] - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
const onLand = (pt) => polygons.some(([outer, ...holes]) => inRing(pt, outer) && !holes.some((h) => inRing(pt, h)));

export const MAP = { w: 1000, h: 420, latTop: 80, latBottom: -56 };
const STEP = 2.2;
const dots = [];
for (let lat = MAP.latTop; lat >= MAP.latBottom; lat -= STEP) {
  for (let lon = -180; lon < 180; lon += STEP) {
    if (onLand([lon, lat])) {
      const x = ((lon + 180) / 360) * MAP.w;
      const y = ((MAP.latTop - lat) / (MAP.latTop - MAP.latBottom)) * MAP.h;
      dots.push(`M${x.toFixed(1)} ${y.toFixed(1)}h0`);
    }
  }
}

writeFileSync(
  new URL('../src/data/world-dots.mjs', import.meta.url),
  `// Generated by scripts/make-map.mjs – do not edit by hand.\nexport const MAP = ${JSON.stringify(MAP)};\nexport const WORLD_PATH = ${JSON.stringify(dots.join(''))};\n`,
);
console.log(`wrote ${dots.length} dots`);
