<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-ai" aria-hidden="true">
  <div class="win">
    <div class="win-bar"><i></i><i></i><i></i><span>ai.your-vps.net – Open WebUI</span></div>
    <div class="chat">
      <p class="msg me">Summarise last week's support tickets</p>
      <p class="msg bot"><span data-stream="Found 128 tickets. 41% were billing questions, 33% DNS changes and 26% performance. Average first response: 6 minutes. Suggested action: publish a DNS guide.">…</span></p>
    </div>
    <div class="chat-input"><span>Ask your private model…</span><b><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m4 12 16-8-6 16-2.5-6.5z"/></svg></b></div>
  </div>
  <div class="toast float-b"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v4M12 17v4M3 12h4M17 12h4M6 6l2.5 2.5M15.5 15.5 18 18M6 18l2.5-2.5M15.5 8.5 18 6"/><circle cx="12" cy="12" r="2"/></svg><div><b>llama3.1:8b</b><small>Running locally · 0 data shared</small></div></div>
</div>
