<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-cloud" aria-hidden="true">
  <svg viewBox="0 0 400 260" class="nodes">
    <g class="links">
      <path d="M200 60 L90 150"/><path d="M200 60 L310 150"/><path d="M90 150 L200 220"/><path d="M310 150 L200 220"/><path d="M200 60 L200 220"/>
    </g>
    
      <g class="node n0" transform="translate(200 60)"><rect x="-46" y="-18" width="92" height="36"/><text y="5">Controller</text></g>
      <g class="node n1" transform="translate(90 150)"><rect x="-46" y="-18" width="92" height="36"/><text y="5">vCloud 1</text></g>
      <g class="node n2" transform="translate(310 150)"><rect x="-46" y="-18" width="92" height="36"/><text y="5">vCloud 2</text></g>
      <g class="node n3" transform="translate(200 220)"><rect x="-46" y="-18" width="92" height="36"/><text y="5">Storage</text></g>
  </svg>
  <div class="toast float-b"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5M12 7v5l3 2"/></svg><div><b>Snapshot created</b><small>vCloud 2 · 2 min ago</small></div></div>
</div>
