<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-dash" aria-hidden="true">
  <div class="dash-card float-a">
    <div class="dash-srv"><span class="srv-ico"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="7" rx="2"/><rect x="3" y="13" width="18" height="7" rx="2"/><path d="M7 7.5h.01M7 16.5h.01M11 7.5h6M11 16.5h6"/></svg></span><div><b>srv-482.rmdhost.net</b><small>Ubuntu 24.04 · Plus Berg</small></div><span class="live">Running</span></div>
  </div>
  <div class="dash-apps float-b"><span>Docker</span><span>Nginx</span><span>WordPress</span><span>n8n</span><span>MySQL</span><span>Node</span><span class="more-dots">•••</span></div>
  <div class="dash-gauges float-c">
<div class="gauge">
  <div class="gauge-top"><span>CPU usage</span><b data-spark-val="cpu">42%</b></div>
  <svg viewBox="0 0 120 36" preserveAspectRatio="none" class="spark"><path data-spark="cpu" d="M0 30 L120 30"/><path class="spark-fill" data-spark-fill="cpu" d="M0 36 L0 30 L120 30 L120 36 Z"/></svg>
</div>
<div class="gauge">
  <div class="gauge-top"><span>Memory usage</span><b data-spark-val="ram">31%</b></div>
  <svg viewBox="0 0 120 36" preserveAspectRatio="none" class="spark"><path data-spark="ram" d="M0 30 L120 30"/><path class="spark-fill" data-spark-fill="ram" d="M0 36 L0 30 L120 30 L120 36 Z"/></svg>
</div></div>
  <div class="dash-chip float-d"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 4.5 3.4 8.3 8 9 4.6-.7 8-4.5 8-9V6z"/><path d="m9 12 2 2 4-4"/></svg> DDoS filtered <b data-counter-live="1284">1,284</b></div>
</div>
