<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-game" aria-hidden="true">
  <div class="win">
    <div class="win-bar"><i></i><i></i><i></i><span>Game panel – survival-01</span></div>
    <div class="game-body">
      <div class="g-stat"><small>Players</small><b data-counter-live="87" data-max="120">87</b><span>/ 120</span></div>
      <div class="g-stat"><small>Tick rate</small><b>20.0</b><span>TPS</span></div>
      <div class="g-stat"><small>Ping</small><b>18</b><span>ms</span></div>
      
<div class="gauge">
  <div class="gauge-top"><span>Server load</span><b data-spark-val="ping">38%</b></div>
  <svg viewBox="0 0 120 36" preserveAspectRatio="none" class="spark"><path data-spark="ping" d="M0 30 L120 30"/><path class="spark-fill" data-spark-fill="ping" d="M0 36 L0 30 L120 30 L120 36 Z"/></svg>
</div>
    </div>
  </div>
  <div class="toast float-b"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 4.5 3.4 8.3 8 9 4.6-.7 8-4.5 8-9V6z"/><path d="m9 12 2 2 4-4"/></svg><div><b>Attack mitigated</b><small>UDP flood · 41 Gbps blocked</small></div></div>
</div>
