<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-rack" aria-hidden="true">
  <div class="rack">
    <div class="unit"><span class="leds"><i style="--d:0s"></i><i style="--d:0s"></i></span><span class="vents"></span><span class="lbl">Mercury</span></div><div class="unit"><span class="leds"><i style="--d:0.37s"></i><i style="--d:0.71s"></i></span><span class="vents"></span><span class="lbl">Venus</span></div><div class="unit sel"><span class="leds"><i style="--d:0.74s"></i><i style="--d:0.21999999999999997s"></i></span><span class="vents"></span><span class="lbl">Uranus</span></div><div class="unit"><span class="leds"><i style="--d:1.1099999999999999s"></i><i style="--d:0.9299999999999999s"></i></span><span class="vents"></span><span class="lbl">Mars</span></div><div class="unit"><span class="leds"><i style="--d:0.08000000000000007s"></i><i style="--d:0.43999999999999995s"></i></span><span class="vents"></span><span class="lbl">Neptune</span></div><div class="unit"><span class="leds"><i style="--d:0.4500000000000002s"></i><i style="--d:1.15s"></i></span><span class="vents"></span><span class="lbl">Saturn</span></div><div class="unit"><span class="leds"><i style="--d:0.8199999999999998s"></i><i style="--d:0.6599999999999999s"></i></span><span class="vents"></span><span class="lbl">Jupiter</span></div>
  </div>
  <div class="dash-card float-a rack-card"><div class="dash-srv"><span class="srv-ico"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="2.5" width="16" height="19" rx="2"/><path d="M4 8.5h16M4 14.5h16M8 5.5h.01M8 11.5h.01M8 17.5h.01M12 5.5h4M12 11.5h4M12 17.5h4"/></svg></span><div><b>Uranus · E-2146G</b><small>6C/12T · 32 GB ECC · RAID 1</small></div><span class="live">Online</span></div></div>
  <div class="dash-gauges float-c rack-g">
<div class="gauge">
  <div class="gauge-top"><span>Network 1 Gbit/s</span><b data-spark-val="net">64%</b></div>
  <svg viewBox="0 0 120 36" preserveAspectRatio="none" class="spark"><path data-spark="net" d="M0 30 L120 30"/><path class="spark-fill" data-spark-fill="net" d="M0 36 L0 30 L120 30 L120 36 Z"/></svg>
</div></div>
</div>
