<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-shield" aria-hidden="true">
  <div class="rings"><i></i><i></i><i></i></div>
  <div class="shield-core"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 4.5 3.4 8.3 8 9 4.6-.7 8-4.5 8-9V6z"/><path d="m9 12 2 2 4-4"/></svg></div>
  <span class="packet" style="--a:0deg;--d:0s"></span><span class="packet" style="--a:45deg;--d:0.35s"></span><span class="packet" style="--a:90deg;--d:0.7s"></span><span class="packet" style="--a:135deg;--d:1.0499999999999998s"></span><span class="packet" style="--a:180deg;--d:1.4s"></span><span class="packet" style="--a:225deg;--d:1.75s"></span><span class="packet" style="--a:270deg;--d:2.0999999999999996s"></span><span class="packet" style="--a:315deg;--d:2.4499999999999997s"></span>
  <div class="toast float-b"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12.5 4.5 4.5L19 7.5"/></svg><div><b>Clean traffic only</b><small>Edge filtering active</small></div></div>
</div>
