<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<span class="tv tv-storage" aria-hidden="true"><div class="tv-grid"></div><div class="tv-sync"><p><span>projects/</span><small>12.4 GB</small><i style="--d:0s"></i></p><p><span>invoices-2026/</span><small>840 MB</small><i style="--d:0.7s"></i></p><p><span>photos/</span><small>96.1 GB</small><i style="--d:1.4s"></i></p><p><span>client-portal/</span><small>3.2 GB</small><i style="--d:2.0999999999999996s"></i></p><p class="tv-hash">sha256 e3b0c442…98fb92427ae41e4649b934ca495991b7852b855</p></div></span>
