<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<span class="tv tv-linux" aria-hidden="true"><canvas class="matrix" data-matrix aria-hidden="true"></canvas>
      <div class="tv-term"><p><b>root@srv-482</b>:~# uptime</p><p class="g">up 182 days, load avg 0.12 0.09 0.05</p><p><b>root@srv-482</b>:~# nproc &amp;&amp; free -h | head -2</p><p class="g">2</p><p class="g">Mem: 8.0Gi used 1.9Gi free 6.1Gi</p><p><b>root@srv-482</b>:~# <span class="cur"></span></p></div></span>
