<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<span class="tv tv-windows" aria-hidden="true"><div class="tv-grid"></div>
      <div class="tv-win"><p class="tv-bar">Performance Monitor — winberg-x8</p>
        <svg viewBox="0 0 200 80" preserveAspectRatio="none" class="tv-graph"><path class="l1" d="M0 60 L20 52 L40 56 L60 40 L80 44 L100 30 L120 36 L140 22 L160 28 L180 18 L200 24"/><path class="l2" d="M0 70 L25 66 L50 68 L75 60 L100 64 L125 58 L150 62 L175 54 L200 58"/></svg>
        <p class="tv-kv"><span>CPU</span><b>23%</b><span>RAM</span><b>3.1/8 GB</b><span>NVMe</span><b>1.2 GB/s</b></p></div></span>
