<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-term" aria-hidden="true">
  <div class="win">
    <div class="win-bar"><i></i><i></i><i></i><span>root@rmdhost: ~</span></div>
    <pre class="term" data-term='["$ rmd deploy --plan ssd-medium --region fra","› Allocating 6 vCores · 12 GB RAM · 100 GB NVMe","› Installing Ubuntu 24.04 LTS ......... done","› Applying DDoS protection profile ..... done","› Configuring IPv4 + IPv6 /64 .......... done","✓ Server online at 185.214.10.42 (38s)","$ ssh root@185.214.10.42"]'></pre>
  </div>
  <div class="toast float-b"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12.5 4.5 4.5L19 7.5"/></svg><div><b>Deployment complete</b><small>Frankfurt · 38 seconds</small></div></div>
</div>
