<?php
/**
 * GENERATED by scripts/build-wp.mjs – do not edit by hand.
 *
 * @package RMDHost
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="scene scene-win" aria-hidden="true">
  <div class="win rdp">
    <div class="win-bar"><i></i><i></i><i></i><span>Remote Desktop – winberg-x8</span></div>
    <div class="rdp-body">
      <div class="rdp-icons"><span><i></i>This PC</span><span><i></i>MetaTrader</span><span><i></i>SQL Server</span><span><i></i>IIS</span></div>
      <div class="rdp-app float-a"><div class="rdp-app-bar">MetaTrader – EURUSD</div><svg viewBox="0 0 200 70" class="candles"><rect x="6" y="15" width="6" height="10" class="down"/><rect x="17" y="40" width="6" height="17" class="up"/><rect x="28" y="37" width="6" height="24" class="up"/><rect x="39" y="34" width="6" height="31" class="down"/><rect x="50" y="31" width="6" height="38" class="up"/><rect x="61" y="28" width="6" height="15" class="up"/><rect x="72" y="25" width="6" height="22" class="down"/><rect x="83" y="22" width="6" height="29" class="up"/><rect x="94" y="19" width="6" height="36" class="up"/><rect x="105" y="16" width="6" height="13" class="down"/><rect x="116" y="41" width="6" height="20" class="up"/><rect x="127" y="38" width="6" height="27" class="up"/><rect x="138" y="35" width="6" height="34" class="down"/><rect x="149" y="32" width="6" height="11" class="up"/><rect x="160" y="29" width="6" height="18" class="up"/><rect x="171" y="26" width="6" height="25" class="down"/><rect x="182" y="23" width="6" height="32" class="up"/><rect x="193" y="20" width="6" height="39" class="up"/></svg></div>
    </div>
    <div class="rdp-taskbar"><span class="start"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 5.5 10.5 4.5v7H3zM12.5 4.2 21 3v8.5h-8.5zM3 12.5h7.5v7L3 18.5zM12.5 12.5H21V21l-8.5-1.2z"/></svg></span><i></i><i></i><i></i><span class="clock" data-clock>12:00</span></div>
  </div>
</div>
